// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportsEventsAPI.Data;

namespace SportsEventsAPI.Migrations
{
    [DbContext(typeof(EventContext))]
    [Migration("20190213205439_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SportsEventsAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name");

                    b.Property<string>("Result");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new { Id = 1, EndDate = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Manchester United VS Paris Saint-Germain", Result = "0-2", StartDate = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 2, EndDate = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Roma VS Paris FC Porto", Result = "2-1", StartDate = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 3, EndDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "FC Viktoria Plzen VS Roma", Result = "2-1", StartDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
